listen: ":6666"
whitelist:
  - telegram.org
  - t.me
  - telesco.pe
  - telegram.me
  - tg.dev
  - 95.161.64.0/20
  - 91.108.4.0/22
  - 91.108.8.0/22
  - 91.108.56.0/22
  - 149.154.160.0/22
  - 149.154.164.0/22
  - 149.154.160.0/23
  - 149.154.162.0/23
  - 149.154.164.0/23
  - 149.154.166.0/23
refresh_interval: 1m
subnet: "fe80::"
subnet_mask: 64
