listen: ":6666"
whitelist:
  - telegram.org
  - t.me
  - telesco.pe
  - telegram.me
  - tg.dev
  - 91.108.16.0/22
  - 149.154.160.0/22
  - 149.154.168.0/22
  - 95.161.64.0/20
refresh_interval: 1m
subnet: "fe80::"
subnet_mask: 64
